version: '3'

services:
  bank-db:
    image: 'postgres:15-alpine'
    container_name: bank-db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=bank
