spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: test
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  encryption:
    key: ryRKW8lntKIJUdmWJh/dBDAzr6kB3aVjBPbJ6z607ck=
    iv: fCIxLGffHE0=